### ISSUE TITLE
How much FPS ?

### ISSUE THREAD

**Issue by wibimaster** [nikogamulin/movidius-rpi#1]
Hi !
Your picture seems to be 1080p, can you tell us at how much FPS it runs with the face detection / recognition ?

Thanks ! :)

**Comment by nikogamulin** [comment]
Hi,
With single Movidius NCS2 And RPi 3, he object detection ran at approx 14 FPS. The image for detection was downsized whereas the display image was the same size as the original. The bounding box coordinates were multiplied by the scaling factor in order to fit the display layout.

**Comment by wibimaster** [comment]
Thanks !

Seems we can have 25FPS with a RPi 4 (https://raspberrypi4u.blogspot.com/)

Have you already tried the Orange Pi AI Stick (light) ?

**Comment by nikogamulin** [comment]
@wibimaster , thank you for mentioning Orange Pi AI Stick. Haven't heard about it before. 
Yes, with RPi 4 it is possible to achieve greater FPS.
